name: Latest beer posts workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '0 0 1 * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         # Replace this URL with your rss feed URL/s
         comment_tag_name: "AGALEWERKS"
         commit_message: "Updated readme with the latest Ag Alewerks data"
         feed_list: "https://blog.agalewerks.com/feed/"
